### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#12]
1. is there chance to auto-login after register account action?
2. how can I set all my accounts to offline (steam friends) - currently show logged - website
3. how can I move down first console log - 2017-06-28T11:26:27.029Z - info: Successfully...  in case of:

```
  ──────────────
  register
(Move up and down to reveal more choices)2017-06-28T11:26:27.029Z - info: Successfully...
2017-06-28T11:26:27.098Z - info: Successfully...
```
4. how can I remove "2017-06-28T11:26:27.098Z" or at least make it like: 2017-06-28 - 11:26:27 / **solved: timestamp: false;**
5. is it possible to do 'Unique Visitors' in VoteBot?

**Comment by SamerAlsayegh** [comment]
1. For auto-login on register it is not a feature yet, but if you wanna do it, just hook to the 'loadedAccount' and just manually trigger a login using `botAccount.Auth.loginAccount([], callback);` By the way, once the account is registered and you restart the bot, the account auto-logins.
2. You can listen to the 'loggedIn' event and run `botAccount.Friends.logout()` on each event that runs.
3.  I don't understand what you mean, can you explain?
4. Yeah you are correct, this can be adjusted to be configurable in a later version
5. Unique Visitors is possible, however, I may not implement it now, but if you wanna add it and send a pull request, I can happily accept it. 
To do it, you just do a similar request as the one for upvotes/downvotes, except you send a GET request to the attachment page and remove options. This is theoretically how it should work, but I have not tested it, so I am not sure.

**Comment by nvmego** [comment]
3. now is like: http://i.imgur.com/KnsK6mz.png
How to move down first log to look like that: http://i.imgur.com/9LYrB7j.png

space between (Move up and down to reveal more choices) and first log with timestamp

**Comment by SamerAlsayegh** [comment]
Oh, that seems to be an issue with the formatting of inquirer.js  I will check how it could be fixed.

**Comment by SamerAlsayegh** [comment]
I tried to look into, but to fix it will either need a major re-work for the GUI or the removal of any logging into console. To be honest It is not that big of an issue to go with either solution. There probably is another simple solution, but just haven't thought of it yet. I will keep it as a side thing for now...

**Comment by nvmego** [comment]
**thanks for the answer**

**Comment by nvmego** [comment]
Hello, can you help me where exactly I should paste `'botAccount.Friends.logout()'` in code?  to set Offline in friends, or just prevent them for login to friends?

I tried in lib/index.js after  `if (botAccounts[botAccountIndex].loggedIn) {` and` botAccount.on('loggedIn', function (botAccount) {`

**Comment by SamerAlsayegh** [comment]
to prevent login, you will need to check loggedIn function under Bot.js at this section:
`self.Friends.login(500, 'web');` commenting it out, should disable login
If you wanted to avoid changing the source, you can hook to the loggedIn event, as such:
`
    /**
     * We are now logged in, thus ready to logout
     */
    botsManager.on('loggedIn', function (botAccount) {
        botAccount.Friends.logout();
    });
`

**Comment by nvmego** [comment]
preventing login works, Thank you 👍

**Comment by nvmego** [comment]
I have question about 'Opting Out': https://www.npmjs.com/package/@doctormckay/stats-reporter

Where I should paste:

    Application authors: set global._mckay_statistics_opt_out to true
    End-users: set the NODE_MCKAY_STATISTICS_OPT_OUT environment variable to 1

to disable doctormckay statistics?

**Comment by SamerAlsayegh** [comment]
I honestly do not know, but I think if you paste it before require'ing node-steam-bot-manager, that should do the trick.

**Comment by egoSB** [comment]
sometimes I getting that error, but script works
```

classes\Community.js:80
            callbackErrorOnly(undefined);
            ^

TypeError: callbackErrorOnly is not a function
```

**Comment by egoSB** [comment]
You can close issue :)
Thanks
