### ISSUE TITLE
create new accounts

### ISSUE THREAD

**Issue by entrailz** [Undeadkillz/node-steam-bot-manager#13]
Hey,

Saw you added the ability to create new accounts in a recent update, but can't seem to get it to work.

Can you please provide some more info on what I will need to do?

When creating the accounts it never seems to actually make an account or save any files.

**Comment by entrailz** [comment]
Added an account (imported) - tried to make a new account and I believe it was made but it didn't save any files.

**Comment by SamerAlsayegh** [comment]
I have gone through the code once more, and it seems I forgot to add the part to save account into account file. Anyways, I fixed the issue, so just run 'npm update' and it should work.

I will leave the issue open for the next few days in case you face any more issues with the functionality.
