### ISSUE TITLE
Incorrect Username / Password handle.

### ISSUE THREAD

**Issue by duffyboyo** [Undeadkillz/node-steam-bot-manager#14]
https://github.com/Undeadkillz/node-steam-bot-manager/blob/5c42e0520ff03b3c7741931b23000f329e26d4f9/lib/index.js#L442  
^ Analytics message

https://github.com/Undeadkillz/node-steam-bot-manager/blob/5c42e0520ff03b3c7741931b23000f329e26d4f9/gui/GUI_Handler.js#L147 

^ One of two instances where incorrect un/password being sent.

Is there a reason you are tracking incorrect passwords and usernames, Curious?

Regards
Duffyboyo

**Comment by SamerAlsayegh** [comment]
You can simply disable stats tracking if you do not wish to send me usage info (it's all anonymous).

Although, the error tracking was done for other issues, I guess this is a fallback of doing so... I will look into it, and remove it in certain cases.  Thanks for reporting it.

**Comment by SamerAlsayegh** [comment]
Alright, please update to the latest version using 'npm update', it addresses this issue. If you notice any more slip-ups, please post them here. Thank you for reporting the issue.

I will keep the issue open for the next few days in case you have any further issues/questions.

Regards,
Samer A.
