### ISSUE TITLE
showing games with drops remaining

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#16]
Hello again ;)

I have small question, is there some easy method to push console.log with appID with available drop cards?

something like this: `[info] {accountname}: you can drop cards in games: {appID}, {appID}.`

I know there is some standalone nodeJS scripts to idle Steam games, but I want to do this on this base script, only show appID without actually idle.

**Comment by SamerAlsayegh** [comment]
You will have to program this feature as an addon. But a good starting point is this:

You will need to get the inventory, but use the app id of 753 (Context ID 6 I think) and then check the Type of the objects in the list to ensure it's a card. This way you can build a list of all cards that you/user owns.

Next, you will need to get a list of all valid cards to compare this list of cards you have to.
I don't know where you can really get that, I couldn't find any API endpoints that list it out. But I saw that there are some API services that offer a list. But not sure.

I know I haven't really given you the exact procedure, but it should be enough to guide you in the right direction.

**Comment by egoSB** [comment]
I guess it will be insanely hard for me without java knowledge

can you help me and at least write simple code for 
https://github.com/DoctorMcKay/node-steamstore#getaccountdatacallback - ownedApps 

is it possible to log in console appID's of owned apps with this function?

**Comment by SamerAlsayegh** [comment]
Yes. You are able to get the owned apps with thst function. Also you are dealing with JavaScript, not Java (2 very different languages, searching for help on Java will only get u Java help on google. And vice versa.) Anyways, to run that function its similar to 

botAccount.store.getAccountData(err, ownedApps, ownedPackages, etc...){/*code here*/}

**Comment by egoSB** [comment]
```
var BotManager = require('node-steam-bot-manager');
var botsManager = new BotManager();

function ownapp() {

    var ownapp = function () {

        for (var botAccountIndex in botsManager.getAccounts()) {

            (function () {
                var botAccount = botsManager.getAccounts()[botAccountIndex];

                botAccount.store.getAccountData(ownedApps, function (err) {
                    if (err)
                        botsManager.errorDebug(botAccount.getAccountName() + ": Error: " + err);
                    else
                        botsManager.infoDebug(botAccount.getAccountName() + ": Owned APPS: " + ownedApp);
                });
			})();
        }
    };
    botsManager.startManager(function (err) {
        setTimeout(ownapp, 20000); 
    });
}

new ownapp();

module.exports = ownapp;
```

I'm close to solution, or not even close? :)

**Comment by SamerAlsayegh** [comment]
Change the parameters of getAccountData to those listed under the function you linked.

err, ownedApps, ownedPackages, etc...

etc... is the rest of the params. There is a quite a bit.

**Comment by egoSB** [comment]
To be honest I don't get it :D
This is a lack of understanding of JavaScript.


```
var BotManager = require('node-steam-bot-manager');
var botsManager = new BotManager();
var SteamStore = require('steamstore');
var store = new SteamStore();

function ownapp() {

    var ownapp = function () {

        for (var botAccountIndex in botsManager.getAccounts()) {

            (function () {
                var botAccount = botsManager.getAccounts()[botAccountIndex];

                botAccount.store.getAccountData(err, ownedApps, ownedPackages, wishlist, ignoredApps, tags, function (err) {
                    if (err)
                        botsManager.errorDebug(botAccount.getAccountName() + ": error: " + err);
                    else
                        botsManager.infoDebug(botAccount.getAccountName() + ": owned apps: " + ownedApp);
                });
			})();
        }
    };
    botsManager.startManager(function (err) {
        setTimeout(ownapp, 20000); 
    });
}

new ownapp();

module.exports = ownapp;
```

getting error: 

```
                botAccount.store.getAccountData(err, ownedApps, ownedPackages, wishlist, ignoredApps, tags, function (err) {
                                                ^

ReferenceError: err is not defined
```

**Comment by SamerAlsayegh** [comment]
Oh, wrap it inside a callback function so like so:


botAccount.store.getAccountData(function(err, ownedApps, ownedPackages, etc...){
/*code here*/
})

**Comment by egoSB** [comment]
works perfectly now, thank you

**Comment by egoSB** [comment]
works perfectly now, thank you
