### ISSUE TITLE
upvoting guides

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#17]
Hello, I'm a bit curious, why votebot doesn't work with community guides.
It looks the same in URL, http://steamcommunity.com/sharedfiles/filedetails/?id=
just different ID, but can't upvote (rate) guide, where is difference?

I getting error: Access Denied

**Comment by SamerAlsayegh** [comment]
Hmm, I think it may be because they use a different API endpoint for that action.

Basically, it's the same URL, but different options seem to be needed to be pass in, I think.

Regardless, I will look into it and add a call for it within the next week or so.

**Comment by egoSB** [comment]
OK, thanks for your time.

**Comment by egoSB** [comment]
Have you found a solution? :)

**Comment by SamerAlsayegh** [comment]
Honestly, I've had it in my to-do list for a while now, and just recently got access to my dev pc, so I will try to maybe get an update in the upcoming few days.

**Comment by egoSB** [comment]
no problem ;)

**Comment by SamerAlsayegh** [comment]
Is the account you are trying to upvote guides through, a limited account? Did you spend a minimum of $5 USD on it?

**Comment by egoSB** [comment]
I'm trying to upvote guide with non-limited accounts for sure (100%).
Limited accounts can't use API.

**Comment by SamerAlsayegh** [comment]
I've tried to find an issue, but it seems like guides should use the same call as all other shared files. I tested the upvote with my accounts, and it seems to have failed 2 out of 3 accounts.


Why...
Well you have to own the game to upvote the guides for it. So if you wanted to upvote guides for CSGO, you must own the game on the bot accounts. You can try this by upvting a guide for a game you do not own on SteamCommunity, it will tell you the following in a prompt:

Access Denied: 
Your account does not have sufficient privileges to perform this action. Please make sure that you own the this game and that your account is in good standing.


If your account does not meet the $5 minimum, it will say InsufficientPrivilege

**Comment by egoSB** [comment]
oh you right! Thanks!
