### ISSUE TITLE
add free games / profile privacy

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#18]
Hello, I'm trying to do something with: https://github.com/DoctorMcKay/node-steam-user#requestfreelicenseappids-callback
but doesn't work, can you help me with my code

**Comment by SamerAlsayegh** [comment]
For the privacy part, you are looking to set the details... To do that you will need to supply parameters in the function, such as below:
```
botAccount.SteamCommunity.profileSettings({profile: 1, comments: 1, inventory: 1, inventoryGifts: 1}, function(err){
/* If an error occured while setting profile settings.*/
});
```

The value of 1 is from this:

```
SteamCommunity.PrivacyState = {
	"Private": 1,
	"FriendsOnly": 2,
	"Public": 3
};
```

For the first part, to get the free ID's, you will do the following:
```
botAccount.SteamUser.requestFreeLicense([88162], function(err, grantedPackages, grantedAppIDs) {
   if (err)
botsManager.errorDebug(botAccount.getAccountName() + ": error: " + err);
   else
botsManager.infoDebug(botAccount.getAccountName() + ": added: " + grantedAppIDs);
});
```


If the title of the code is as such:
requestFreeLicense(appIDs[, callback])

That means you must supply AppIDs as the first parameter, and the second parameter is optional but must be a function which has whatever the callback returns. It might be tough at first, but generally, once you grasp it, all JS coding follows this set-up for calls that do not return a value instantly... (Of course there is other ways, such as Promises, but you probably won't need them for Node Steam Bot Manager)

**Comment by egoSB** [comment]
Thank you for your help.
Profile privacy works great.

But I have some problem with: requestFreeLicense

copied line: botAccount.SteamUser.requestFreeLicense([88162], function(err, grantedPackages, grantedAppIDs) {

and getting error:  **TypeError: Cannot read property 'requestFreeLicense' of undefined**

**Comment by SamerAlsayegh** [comment]
Oh, replace 'SteamUser' with 'client'

Also for 'SteamCommunity', I recommend using 'community'

**Comment by egoSB** [comment]
everything works, thank you again ;)
