### ISSUE TITLE
adding games

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#19]
Today is the day you can add steam game for free: http://store.steampowered.com/app/368420/Mirage_Arcane_Warfare/

my code doesn't work

code of license is: 205872

console log: info: [accountname]: added games: 
its just empty

what is wrong?

**Comment by SamerAlsayegh** [comment]
'grantedPackages' might be empty, but I think the 'grantedAppIDs' variable might be populated.

**Comment by egoSB** [comment]
I forgot to say, I tried that and even forgot to change code, I have in code: + grantedPackages + grantedPackages

maybe something wrong with node-steam-user

**Comment by SamerAlsayegh** [comment]
Hrmm, possibly. I personally never used this functionality in node-steam-user. I would recommend checking up with them.
