### ISSUE TITLE
TradeScript - sending all items to TRADE URL

### ISSUE THREAD

**Issue by flacky90** [Undeadkillz/node-steam-bot-manager#23]
Hello, is there any chance to create tradescript who can send all tradable steam items and game items (from all games from inventory) to 'Trade URL - You can share this unique URL with other Steam users to allow them to send you a trade offer even if they aren't on your friends list. You can share this URL anywhere, including on third-party trading sites and Steam Community groups.' (example: https://steamcommunity.com/tradeoffer/new/?partner=2222222222&token=tve3-neX)

**Comment by flacky90** [comment]
I'm trying to send all steam items (trading cards, emotes, backgrounds) to URL with token

https://pastebin.com/Mijrt03y

I don't know what I'm doing wrong, probably everything because my knowledge is near 0.
Please help. I'm getting error: 

```
offer.addMyItems(inventory);
                                      ^

TypeError: Cannot read property 'addMyItems' of undefined```

**Comment by SamerAlsayegh** [comment]
When you create an offer, you will need to pass any code dealing with the offer into the callback. Such as the example below:
```
botAccount.Trade.createOffer(partner, user_token, function (err, currentOffer) {
  if (err) {
    // Handle an error in creating the offer
  } else {
    // No errors in creating the offer, we can now add our items.
  }
});
```

You may omit the user token if you are friends with the bot, but partner is required. Please refer to node-steam-tradoffer-manager for more details.

Also in the partner, you can pass the trade-url which will have both the partner and the token, so you may omit it from the call, and simply pass in the trade url.

**Comment by flacky90** [comment]
Thank you for your help!
