### ISSUE TITLE
Steam queue

### ISSUE THREAD

**Issue by flacky90** [Undeadkillz/node-steam-bot-manager#24]
Hello, I need your help :)

I'm trying to do script for: http://store.steampowered.com/explore/

Already somebody smart created useful script for web browser: https://pastebin.com/vZWDY1YW
I want to try convert this script to Node.js step by step. Unfortunately I stuck at 401 response (unautorized).

Here is my code: https://pastebin.com/qzG4E1Yg

Please help me :)
Greetings.

**Comment by SamerAlsayegh** [comment]
Unfortunately there is no built-in method for exploring Queue's. However, you can use the code that other person did and just use the botInfo.Request.getRequest and botInfo.Request.postRequest
and pass in the data for any postRequests the sessionid which can be fetched from 'botAccount.Auth.sessionid'

It shouldn't be too complicated, however you can contact me on Steam for further help.
