### ISSUE TITLE
getting nicknames from accounts

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#25]
I trying to do simple script to grab Steam nickname of current account, but even with it I'm failing.
Works good in my idler script

```
	bot.on("accountInfo", function(name) {
		console.log("Your Online Name: " + name);
	});
```

but this doesn't work,

```
var BotManager = require('node-steam-bot-manager');

function myNick() {
    var botsManager = new BotManager();

    botsManager.on("accountInfo", function(name) {
		botsManager.infoDebug(botAccount.getAccountName()+ ": your nickname ->" + name);
    });
    botsManager.infoDebug("Starting...");
    botsManager.startManager(function (err) {
        if (err)
            botsManager.errorDebug("Failed to start.");
    });
}

new myNick();

module.exports = myNick;
```

I found this: https://github.com/DoctorMcKay/node-steam-user#accountinfo
but I don't really get it, where I should put this to grab current nickname?

**Comment by SamerAlsayegh** [comment]
You can call getDisplayName() on the botAccount object you get from a loggedIn event...
Try to listen to 'loggedIn' and fetch the botAccount from the callback.

Such as below:

```
    botsManager.on("loggedIn", function(botAccount) {
		botsManager.infoDebug(botAccount.getAccountName()+ ": your nickname ->" + name);
    });
```
I will be updating the library now to include node-steam-user functionality and also further fixes.

**Comment by nextTOPMODEL** [comment]
should I change only these line above?

Getting something like that:
https://i.imgur.com/3o0MSKm.png

getDisplayName() showing name between [ ] in menu of bot? if yes, I have everywhere undefined

**Comment by SamerAlsayegh** [comment]
I don't believe I use the accountInfo event in my code though. So that is what It is better to just call botAccount.getDisplayName() just as I sent earlier.

**Comment by nextTOPMODEL** [comment]
fixed, thanks!
