### ISSUE TITLE
grabbing number of 'Titles Viewed In Queue'

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#29]
how can I grab number of 'Titles Viewed In Queue' (showed here: http://store.steampowered.com/explore/) and show this number in nodejs console?

**Comment by SamerAlsayegh** [comment]
I don't believe there is an API endpoint for such info. What you can do is maybe load it via Cheerio or similar library and then parse out the info you need. But I may be wrong about the API endpoint not existing.

**Comment by nextTOPMODEL** [comment]
OK, I will take a look, thanks for advice.
