### ISSUE TITLE
Steam Market sell listing

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#31]
Hello again :)

I have a few accounts where I idle steam games for cards and 1 storage account.
I transferred all steam trading cards (for 1 game) to storage account, and I have ~1000 cards to sell (they are all from one game).
I want to put them on Steam market (I know I can use SIH chrome extension or something different but I prefer nodejs method).

I found something: https://dev.doctormckay.com/topic/287-automatic-market-seller/#entry746
but I really don't know how to use it, do you know how to implement this? like I want to put all steam items to steam market for fixed price?

I will confirm market listings on phone.
Greetings.

EDIT: I even found something like this: https://github.com/Z8pn/node-steam-market
but how can I use it in your script? to loop all cards and put them on market?

**Comment by SamerAlsayegh** [comment]
Well your faced with either building your own method to do selling (method 1 you proposed).
Or passing in the cookie and session data as in method 2.

To do method 2, check the Classes/Community.js file where I use the session, but I'm not sure about the cookie part. So I'd recommend instead to use method 1 and build your own method for selling

**Comment by nextTOPMODEL** [comment]
Thank you for advice.

I trying to do something with it, but I will be 100% honest, I have no idea what I am doing :D
Please help me :)

I'm trying to sell all steam cards (it's storage account, all cards are same) for fixed price.

ATM I getting error 400, but I know there is some big mistake.
I don't know how I should put every card on market.

My code:
https://pastebin.com/LJzZ7J8i


Greetings.

**Comment by SamerAlsayegh** [comment]
Simply loop. But once you list the item, you will also need to confirm outstanding trades. There is an appropriate method under Trade. But I haven't tested market listing before, so I am not entirely sure of reliability.

**Comment by nextTOPMODEL** [comment]
I already fixed it before, but I forgot to say that :D
Thank you for advices like always :)
Greetings
