### ISSUE TITLE
card checker

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#32]
Hello, I'm trying to do card idle checker, if some account have some cards to idle.
I'm too dumb for this ^^

Source: https://github.com/DoctorMcKay/Steam-Card-Farmer/blob/old-cli/farmer.js

I'm trying to check if any account have some games to idle, if {YES} how many games.
Can you help me?

my code returning: null

```
var BotManager = require('node-steam-bot-manager');
var request = require('request');
var Cheerio = require('cheerio');
var botsManager = new BotManager();

function cardChecker() {

    var checkCards = function () {

        for (var botAccountIndex in botsManager.getAccounts()) {

            (function () {
                var botAccount = botsManager.getAccounts()[botAccountIndex];

		var g_Jar = request.jar();
		request = request.defaults({"jar": g_Jar});
		request("https://steamcommunity.com/my/badges/?p=1", function(err, response, body) {
			
			botsManager.infoDebug("request sent! " + botAccount.getAccountName());
			
			var $ = Cheerio.load(body);
				var row = $(this);
				var drops = row.find('.progress_info_bold').text().match(/(\d+)/);
				botsManager.infoDebug("games to idle: " + drops + " - " + botAccount.getAccountName());

			});
            })();
        }
};
    botsManager.startManager(function (err) {
        setTimeout(checkCards, 5000);
    });
}

new cardChecker();

module.exports = cardChecker;
```

**Comment by SamerAlsayegh** [comment]
Your code seems correct, however  I never used Cheerio, which seems to be the part you need help with. I'd just keep testing or looking up docs for Cheerio

**Comment by RedSparr0w** [comment]
The following **_should_** work
```javascript
var apps_with_drops = 0,
    total_drops = 0;
var $ = Cheerio.load(body);
$('.badge_row').each(function() {
  var row = $(this);
  var drops = row.find('.progress_info_bold').text().match(/(\d+)/);
  if(!drops) {
    return;
  }

  drops = parseInt(drops[1], 10);
  if(isNaN(drops) || drops < 1) {
    return;
  } else {
    apps_with_drops++;
    total_drops += drops;
  }
});
botsManager.infoDebug(`${total_drops} card drops remaining across ${apps_with_drops} games - ${botAccount.getAccountName()}`);
```
**Note:**
This will only check the first page `?p=1` (150 per page),
You will need to add aditional checks to see if there is a 2nd page that needs checking.

**Comment by nextTOPMODEL** [comment]
thank you for interesting


this is my code:

https://pastebin.com/DGmLwRCZ


Most of my accounts are ~10 lvl so I don't need to check page 2 because, they don't have much badges.
I'm checking this code on account who has 3 games to cards idle, and it's 100% logged (autologin). 

0 card drops remaining across 0 games - accountname


I think something is wrong with request, console.log($), should give some info about body if it's loaded properly or no?

**Comment by RedSparr0w** [comment]
Ahh, i think it will be because the cookies are not set before you send the request.
In `farmer.js` they are set on [this line](https://github.com/DoctorMcKay/Steam-Card-Farmer/blob/old-cli/farmer.js#L85-L89).
Not sure how to go about it on `node-steam-bot-manager` though (i haven't gotten around to using it yet)

**Comment by SamerAlsayegh** [comment]
I rewrote the code slightly to make it more efficient and work as you require. The change is now the requests will be fired when the bots login. Furthermore, I made it use the built-in request object that is used for other API calls, hence you don't need to provide any Session or Cookie data.

Let me know if you have any issues.

```
var BotManager = require('node-steam-bot-manager');
var Cheerio = require('cheerio');
var botsManager = new BotManager();

function cardChecker() {

    botsManager.on('loggedIn', function (botAccount) {
        botAccount.Community.community.httpRequestGet('https://steamcommunity.com/my/badges/?p=1', function (error, response, body) {
            botsManager.infoDebug("request sent! " + botAccount.getAccountName());

            var apps_with_drops = 0,
                total_drops = 0;
            var $ = Cheerio.load(body);
            $('.badge_row').each(function() {
                var row = $(this);
                var drops = row.find('.progress_info_bold').text().match(/(\d+)/);
                if(!drops) {
                    return;
                }

                drops = parseInt(drops[1], 10);
                if(isNaN(drops) || drops < 1) {
                    return;
                } else {
                    apps_with_drops++;
                    total_drops += drops;
                }
            });
            botsManager.infoDebug(`${total_drops} card drops remaining across ${apps_with_drops} games - ${botAccount.getAccountName()}`);
        });
    });

    botsManager.startManager(function (err) {

    });
}

new cardChecker();

module.exports = cardChecker;
```

**Comment by nextTOPMODEL** [comment]
Thank you guys! everything works now :)

but there is a small problem, script grabbing 'tasks completed' of 'Pillar of Community' badge
is there any way to exclude row with 'badges/2'

`'card drops remaining: 11 - across 1 games.'`

script takes 'tasks' and count as a game: https://i.imgur.com/WYXAvwu.png

for now I just added:

```
            if (apps_with_drops >= 2) {
			botsManager.infoDebug(`${botAccount.getAccountName()}: card drops remaining: ${total_drops} - across ${apps_with_drops} games.`);
			} else {};
```

and it showing accounts with 2 games to drop or just 1 game to drop + bugged 'community' badge

Thank you, greetings.

**Comment by nextTOPMODEL** [comment]
I can't believe :D I found solution by myself with simple trick :D

just need to add: `$('div.badge_row:has(a.badge_row_overlay[href$="/badges/2"])').remove();`
after `var $ = Cheerio.load(body);`

Thank you guys for help!
I appreciate it.
