### ISSUE TITLE
disconnecting from Steam

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#35]
I want to close connection after action, like after group join etc, only for 1 bot instance

I tried to use:
```
botAccount.Auth.logoutAccount();
botAccount.logoutAccount();
botAccount.client.logOff();
botAccount.client.disconnect();
```

looks like 'netstat -b' still shows established connection for node.exe.

example of code:

```
botAccount.Community.joinGroup(groupID, function (err) {
        if (err)
            botsManager.errorDebug("Failed to join group. " + err);
        else
           botAccount.Auth.logoutAccount();
           botAccount.client.logOff();
           botAccount.client.disconnect();
           botsManager.infoDebug("Successfully joined group with  " + botAccount.getAccountName());
});
```

I just want to cut connection when finished (only per account).

Can you please help me? 😃 

btw. I'm using version before 'heavy update'.

**Comment by SamerAlsayegh** [comment]
Yeah I am aware of the issue, however, I can't figure out if the issue is from node-steam library or DoctorMkay's library (since I route connections through there), or if it is a Linux/NodeJS issue (since the connection is technically complete but remains as idle). 

By any chance, are you using a Linux OpenVZ vps?


As a temporary workaround you can restart the bots every few hours, and if you do not use the trading system, disable trade polling, as that causes a 'socket' leak after a few hours with 30+ bots.

**Comment by xc4t** [comment]
first of all, I'm not using any VPS, I'm using nodejs locally on windows 10

I tried everything to disconnect account from Steam after some action like/group join etc, but I failed every time :/

its not DoctorMcKay library issue, because I using steam idler for idling game cards

open source code: https://pastebin.com/fQkhsuRX

I wanted to test it and I edited this function

```
bot.on("friendMessage", function(steamID, message) {
    console.log("[" + this.username + "] Message from " + steamID+ ": " + message);
    bot.disconnect();
});
```

I added **bot.disconnect();** and it works, when I message to account who idling games, its going instant offline and connection is closed with 'netstat -b'

**Comment by SamerAlsayegh** [comment]
Hrmm, try adding a 'timeout' to the request under classes/Request based on the request you are using?

For example
```
Request.prototype.postRequest = function (url, data, callback) {
    var self = this;
    self.request({
        url: url,
        method: "POST",
        json: true,
        form: data
    }, function (err, response, body) {
        callback(err, body);
    });
};
```

is now 
```
Request.prototype.postRequest = function (url, data, callback) {
    var self = this;
    self.request({
        url: url,
        method: "POST",
        json: true,
        timeout: 10000,
        form: data
    }, function (err, response, body) {
        callback(err, body);
    });
};
```

Does that close the connection? I have only been having it with trade-polling, so I don't know if other functionality has the same issue too?

**Comment by xc4t** [comment]
I'm using POST requests, I edited this, and nothing changed, connection is still 'ESTABLISHED' even after 20 sec
```
TCP    10.2.185.188:52734     a104-81-216-214:https  ESTABLISHED
[node.exe]
```

I guess post request is done and connection is closed, but account is still logged to steam servers, thats why I see 'ESTABLISHED' connection, I need to figure out how to disconnect logged account from steam servers after action (like/group join).

**Comment by xc4t** [comment]
I updated all DoctorMcKay repositories and it looks like everything works as it should.
