### ISSUE TITLE
weird question about executing nodejs script

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#36]
Hello, I have really weird question, is it possible to execute other nodejs script 

something like that:

```
                        botAccount.Community.followPublisher(profileId, function (err) {
                            if (err)
                                botsManager.errorDebug("Failed to follow user. User might already be followed. Error: " + err);
                            else
                                "node FavouriteBot.js";
                                botsManager.infoDebug("Successfully followed user with  " + botAccount.getAccountName());
});
```

I mean, executing new script  **"node FavouriteBot.js";** when follow is done.
I know I can copy paste code to favbot, but I want to know if I can execute external script with new nodejs console

**Comment by SamerAlsayegh** [comment]
I believe you can fork it as a process.
More info:
https://stackoverflow.com/questions/13371113/how-can-i-execute-a-node-js-module-as-a-child-process-of-a-node-js-program

**Comment by xc4t** [comment]
everything works very well, thank you very much for advice, you always know everything 👍
