### ISSUE TITLE
gamesPlayed

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#37]
Hello, I'm trying to run game with:

https://github.com/DoctorMcKay/node-steam-user#gamesplayedapps-force

I'm using  botAccount.client.gamesPlayed(["730"]); but looks like doesn't work, is there any way to make it work with gamesPlayed?

**Comment by SamerAlsayegh** [comment]
What is the error exactly? If it is saying that the method does not exist, then perhaps try updating node-steam-user in node-steam-bot-manager. If it is another error, please post it so that I can take a look.

**Comment by RedSparr0w** [comment]
I believe the error message might be:
```console
Uncaught Error: Illegal value for Message.Field .CMsgClientGamesPlayed.GamePlayed.steam_id_gs of type uint64: object (no array expected)
```
Side note: I **_think_** you need to use numbers, as strings will be taken as a `custom game`:
```javascript
botAccount.client.gamesPlayed(["My Custom Game", 730]);
```
Will show `playing non-steam game My Custom Game` on your profile.

**Comment by nextTOPMODEL** [comment]
I'm logged on account in web browser to check if account is in any game, but it doesn't work.
Account is just 'online'

I don't see any error in nodejs console.
Doesn't even work with: `botAccount.client.gamesPlayed(["My Custom Game", 730]);`
0 errors in console, I'm sure I have 730 (csgo on account), when I close nodejs console game is still played 2 days ago (so didnt start with nodejs)

**Comment by RedSparr0w** [comment]
@nextTOPMODEL Did you figure out a fix for this?

**Comment by xc4t** [comment]
no, I didn't, but I guess it doesn't work maybe because I'm using older version: 1.0.53
