### ISSUE TITLE
adding accounts from .txt

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#39]
Hello, I want to add accounts from .txt file to script.

Usually I'm running nodejs onlyGUI and registering accounts one by one, but now I want to add accounts from txt file.
I'm have in .txt a few accounts, they look like this:

login:password
login2:password2
login3:password3
login4:password4

enter after every line and ':' between login and password, how can I automaticly add them to gui handler?

I think I can deal with array maybe, something like this to read .txt file
```

var fs = require("fs");
var array = fs.readFileSync('accounts.txt').toString().split("\n");
```

but how can I add them to account list in script, can you please guide me?
Greetings

**Comment by SamerAlsayegh** [comment]
Hey, what you can do is once you have the list of accounts, assuming in a list as you explained

Then what u can do is a recursive function like below:

```
    let registerAccount = function (array, callback, index){
        if (index == null) index = 0;

        if (array.length > index) {
            console.log(array[index].split(":"));
            botsManager.registerAccount(array[index].split(":")[0], array[index].split(":")[1], {accountName: array[index].split(":")[0], password: array[index].split(":")[1]}, function (err, botAccount) {
                if (err){
                    console.log("Failed to register account: ", array[index].split(":")[0]);
                }
                registerAccount(array, callback, ++index);
            })
        } else {
            console.log("Done!");
        }
    };
    console.log(array);
    registerAccount(array);
```

This is a very quick snippet, it should work, but it may or may not have issues. This would split each line into username and password then pass it into the registerAccount function under botsManager class. Once the bot logs in, it will save the account details as a file (basically importing). If the accounts have other data such as 2fa, you will need to pass it in to the 3rd parameter of registerAccount.

**Comment by xc4t** [comment]
how can I remove \r from password form

`{"username":"login","password":"mypassword\r"}`

looks like script adding \r to every password form

rest is working good (I think) - thank you!

**Comment by SamerAlsayegh** [comment]
could just do array[index].split(":")[1].split("\r")[0]
or array[index].split(":")[1].replace("\r", "")
I think any of the two would work...

**Comment by xc4t** [comment]
everything works good now, tested with 5 accounts, thank you very much!

**Comment by xc4t** [comment]
I have 2 more questions:

1. https://i.imgur.com/abg5yVH.png - how can I use CTRL + V here to paste code? because at the moment I need to use right mouse click and paste function, I wanted to do it with shortcut CTRL + V but it doesn't work

2. https://i.imgur.com/EDQ7A3J.png - after successfully logon on account, is there any simple fix to remember last position in list? because if I adding a lot of accounts I need to scroll a lot, or maybe other easy method like removing account after successfully logon (so it will be moved into deleted folder - so I can grab all added accounts later)

**Comment by SamerAlsayegh** [comment]
1. I wouldn't know if that is possible, you may have to refer to the library I use for the menus InquirerJS
2. You can either maintain an array of completed accounts and save it to a file. Or do the unregisteration, which is a better solution since at some point you may have too many registered accounts that the system can't handle.

**Comment by xc4t** [comment]
okay! thanks for advice!

**Comment by RedSparr0w** [comment]
1. It depends on the console you are using, for example [`cmder`](http://cmder.net/) allows you to use `CTRL+V` to paste

**Comment by xc4t** [comment]
I'm using default windows cmd, its weird because in other nodejs scripts I can easily past text into console with ctrl + v
