### ISSUE TITLE
logging with web browser

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#41]
Hello, I wonder if I can login with web browser (firefox/chrome) to Steam with informations from .dat (username, oauth, steamguard), or its not possible?

**Comment by SamerAlsayegh** [comment]
Depends, what functionality are you looking to do? But generally yes, just use the Request class which will automatically put the auth information for the respective bot. All you gotta do is specify if it's a GET request or POST request.

**Comment by xc4t** [comment]
I have a few Steam accounts, I'm using chrome profiles to browsing each steam profile etc.
I was wonder if I can use somehow informations from .dat file to login on Steam account with single click.
Manging accounts with chrome profile and switching between its pretty annoying + each chrome profile takes nearly 100 mb on disc

Do you think its possible to create some script (I dont know, maybe in .bat) to run chrome (reading file with username login .dat - login;oauth;steamguard) + doing post request to easy login to steam?

I'm mostly managing accounts with nodejs, but I want to use GUI (steam with web browser) sometimes too, because I trading steam card + crafting badges

**Comment by xc4t** [comment]
or maybe chrome extension should be better - reading all files with .dat extension from folder and draw it in some menu (with searchbox), and doing some steam switcher (reading info from .dat and sending post request),  you think is it possible?

**Comment by SamerAlsayegh** [comment]
Honestly that approach seems pretty complicated. If you have a few set of predetermined actions u do on each account u can prob build a nodejs script. Otherwise importing and exporting into chrome profiles is complicated in it's own way.

**Comment by xc4t** [comment]
ok, I get it, thank you for help!
