### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by HanGuiZhu** [Undeadkillz/node-steam-bot-manager#5]
![image](https://cloud.githubusercontent.com/assets/20395051/25178369/235b88da-2538-11e7-9f84-27dfa7f77eb7.png)
I met this problem
I met this problem
What should I do
thank you

**Comment by SamerAlsayegh** [comment]
Hey, sorry for the late reply...

Did you happen to edit the config.json or not yet? If you did, save a backup of it, and rename it. Then re-run the tool.

If that does not work, edit the config and change 'debug' to 'true', and re-run the program and send me the log file.

Regards!

**Comment by SamerAlsayegh** [comment]
I will be closing this issue, if you happen to experience it again, please open a new issue with the information I asked for.

Regards!
