### ISSUE TITLE
Add new Steam Account via API

### ISSUE THREAD

**Issue by 0zguner** [Undeadkillz/node-steam-bot-manager#9]
I've not really dig deep in source code but is it possible to add new steam accounts through api ?

**Comment by SamerAlsayegh** [comment]
Yes it is possible, simply use from the BotManager instance following method:
BotManager.prototype.registerAccount = function (username, password, options, callback)
which can be found [here](https://github.com/Undeadkillz/node-steam-bot-manager/blob/master/lib/index.js#L267)
I have not done documentation on it, however options is just an object containing 'steamguard', 'oAuthToken', 'displayName'. You can get away with just supplying 'steamguard' or 'oAuthToken', not both.

If you need help, contact me on Steam, and I can try to guide you. (I'll keep this issue open for the next few days incase you have further issues. However for questions, I'd recommend you contact me on Steam, my link is in the ReadMe.)

**Comment by 0zguner** [comment]
@Undeadkillz hey, thanks for quick response. I like the project a lot. I was building the same thing like this project. I might work on your project if you have a roadmap

**Comment by SamerAlsayegh** [comment]
I do not at this time, I might make one in the future... Right now I'm checking how often it is used, and based on that I will either further develop it or just maintain it enough for fixes.
